/*
 * Generated by XDoclet - Do not edit!
 */
package com.zoo;

/**
 * Local interface for Tiger.
 * @generated 
 * @wtp generated
 */
public interface TigerLocal
   extends javax.ejb.EJBLocalObject
{

}
