/*
 * Generated by XDoclet - Do not edit!
 */
package com.zoo;

/**
 * Remote interface for Tiger.
 * @generated 
 * @wtp generated
 */
public interface Tiger
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    */
   public java.lang.String roar(  )
      throws java.rmi.RemoteException;

}
