#
# Makefile
#
# Autor: H.Drachenfels
# Erstellt am: 12.09.2003
#

CXX = g++
CXXFLAGS = -g -Wall -ansi -pedantic

all: Aufgabe2

clean:
	rm -f Aufgabe2 Aufgabe2.o

Aufgabe2: Aufgabe2.o
	$(CXX) $(CXXFLAGS) Aufgabe2.o -o Aufgabe2

Aufgabe2.o: Aufgabe2.cpp

