/*
 * Generated by XDoclet - Do not edit!
 */
package de.vsys.ueb.converter;

/**
 * Local home interface for Converter.
 * @generated 
 * @wtp generated
 */
public interface ConverterLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConverterLocal";
   public static final String JNDI_NAME="ConverterLocal";

   public de.vsys.ueb.converter.ConverterLocal create()
      throws javax.ejb.CreateException;

}
