/*
 * Generated by XDoclet - Do not edit!
 */
package de.vsys.ueb.converter;

/**
 * Local interface for Converter.
 * @generated 
 * @wtp generated
 */
public interface ConverterLocal
   extends javax.ejb.EJBLocalObject
{

}
