/*
 * Generated by XDoclet - Do not edit!
 */
package de.vsys.ueb.converter;

/**
 * Home interface for Converter.
 * @generated 
 * @wtp generated
 */
public interface ConverterHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Converter";
   public static final String JNDI_NAME="Converter";

   public de.vsys.ueb.converter.Converter create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
