#
# Makefile
#
# Autor: H.Drachenfels
# Erstellt am: 10.09.2003
#

CXX=g++
CXXFLAGS = -g -Wall -ansi -pedantic

all: Aufgabe1

clean:
	rm -f Aufgabe1 Aufgabe1.o

Aufgabe1: Aufgabe1.o
	$(CXX) $(CXXFLAGS) Aufgabe1.o -o Aufgabe1

Aufgabe1.o: Aufgabe1.cpp

