#
# Makefile
#
# Autor: H.Drachenfels
# Erstellt am: 3.11.2003
#

CXX = g++
CXXFLAGS = -g -Wall -ansi -pedantic

all: Aufgabe4

clean:
	rm -f Aufgabe4 Aufgabe4.o

Aufgabe4: Aufgabe4.o
	$(CXX) $(CXXFLAGS) Aufgabe4.o -o Aufgabe4

Aufgabe4.o: Aufgabe4.cpp

