#
# Makefile
#
# Autor: H.Drachenfels
# Erstellt am: 23.10.2003
#

CXX = g++
CXXFLAGS = -g -Wall -ansi -pedantic

all: Aufgabe3

clean:
	rm -f Aufgabe3 Aufgabe3.o

Aufgabe3: Aufgabe3.o
	$(CXX) $(CXXFLAGS) Aufgabe3.o -o Aufgabe3

Aufgabe3.o: Aufgabe3.cpp

